<?php

namespace App\Console\Commands;

use App\Support\Training\TrainingCatalog;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Keeps the written training material in step with the chapters file:
 *
 *   docs/training/ADMIN_PACKAGE_CREATION_VIDEO_SCRIPT.md   the recording script
 *   tools/training-video/chapters.json                     titles for the recorder
 *
 * Both are generated from resources/data/admin-video-training.php (and the
 * recorded lengths in manifest.json, when present). Edit the chapters file,
 * never the outputs.
 */
class WriteTrainingScript extends Command
{
    protected $signature = 'training:write-script';

    protected $description = 'Regenerate the video training script document and the recorder chapter list';

    public function handle(): int
    {
        TrainingCatalog::flush();
        $chapters = TrainingCatalog::chapters();
        $categories = TrainingCatalog::categories();

        File::ensureDirectoryExists(base_path('tools/training-video'));
        File::put(base_path('tools/training-video/chapters.json'), json_encode(
            collect($chapters)->map(fn ($c) => [
                'number' => $c['number'],
                'title' => $c['title'],
                'description' => $c['description'],
                'category' => $categories[$c['category']]['title'],
            ])->all(),
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,
        )."\n");

        File::ensureDirectoryExists(base_path('docs/training'));
        File::put(base_path('docs/training/ADMIN_PACKAGE_CREATION_VIDEO_SCRIPT.md'), $this->script($chapters, $categories));

        $this->info('Wrote docs/training/ADMIN_PACKAGE_CREATION_VIDEO_SCRIPT.md and tools/training-video/chapters.json ('.count($chapters).' chapters).');

        return self::SUCCESS;
    }

    private function script(array $chapters, array $categories): string
    {
        $demo = json_decode(File::get(resource_path('data/training-demo-package.json')), true);
        $total = TrainingCatalog::totalDuration();
        $keys = array_keys($chapters);

        $out = [];
        $out[] = '# Admin Package Creation — Video Training Script';
        $out[] = '';
        $out[] = '> Generated by `php artisan training:write-script` from `resources/data/admin-video-training.php`. Do not edit by hand — change the chapters file and regenerate.';
        $out[] = '';
        $out[] = '**What the video shows:** the real Universal Brothers admin panel building one complete Hajj package, from signing in to the published page, then editing, duplicating, reusable information and templates.';
        $out[] = '';
        $out[] = "**The package:** \"{$demo['basics']['name']}\", code `{$demo['basics']['code']}`. Every customer-facing value is copied from the approved brochure package **{$demo['source_package']}**. It exists only in the separate training-recording database, where it is marked \"{$demo['training_marker']}\" in its internal notes. Nothing in the recording touched production or the testing database.";
        $out[] = '';
        $out[] = '**Format:** 1280×720 screen recording of the running admin panel. Each chapter opens with a title card; captions on screen describe every action; a caption file (WebVTT) carries the same text. There is no voice narration (see ADMIN_VIDEO_GUIDE_STRUCTURE.md).';
        $out[] = '';
        $out[] = '**Chapters:** '.count($chapters).($total ? ' · **Recorded length:** '.intdiv($total, 60).' min '.($total % 60).' s' : ' · not yet recorded');
        $out[] = '';
        $out[] = '| # | Chapter | Category | Length | Difficulty |';
        $out[] = '|---|---|---|---|---|';
        foreach ($chapters as $c) {
            $out[] = "| {$c['number']} | [{$c['title']}](#chapter-{$c['number']}) | {$categories[$c['category']]['title']} | ".TrainingCatalog::formatDuration($c['video']['duration'] ?? null)." | {$c['difficulty']} |";
        }

        foreach ($chapters as $key => $c) {
            $index = array_search($key, $keys, true);
            $next = isset($keys[$index + 1]) ? $chapters[$keys[$index + 1]] : null;

            $out[] = '';
            $out[] = '---';
            $out[] = '';
            $out[] = "<a id=\"chapter-{$c['number']}\"></a>";
            $out[] = "## {$c['number']}. {$c['title']}";
            $out[] = '';
            $out[] = "*{$categories[$c['category']]['title']} · {$c['difficulty']} · about {$c['task_minutes']} min to do".($c['video'] ? ' · video '.TrainingCatalog::formatDuration($c['video']['duration']) : '').'*';
            $out[] = '';
            $out[] = "**Title card:** Chapter {$c['number']} — {$c['title']} — {$c['description']}";
            $out[] = '';
            $out[] = "**Objective:** {$c['objective']}";
            $out[] = '';
            $out[] = '**Actions performed (in order):**';
            $out[] = '';
            foreach ($c['steps'] as $i => $step) {
                $out[] = ($i + 1).". {$step}";
            }
            if ($c['fields']) {
                $out[] = '';
                $out[] = '**Fields completed and example values:**';
                $out[] = '';
                $out[] = '| Field | Example value |';
                $out[] = '|---|---|';
                foreach ($c['fields'] as [$field, $value]) {
                    $out[] = '| '.str_replace('|', '\\|', $field).' | '.str_replace('|', '\\|', $value).' |';
                }
            }
            $out[] = '';
            $out[] = "**Why it matters:** {$c['why']}";
            if ($c['mistakes']) {
                $out[] = '';
                $out[] = '**Common mistakes:**';
                $out[] = '';
                foreach ($c['mistakes'] as $m) {
                    $out[] = "- {$m}";
                }
            }
            if ($c['check']) {
                $out[] = '';
                $out[] = '**What the admin should check:**';
                $out[] = '';
                foreach ($c['check'] as $m) {
                    $out[] = "- {$m}";
                }
            }
            if ($c['notes']) {
                $out[] = '';
                $out[] = '**Important notes:**';
                $out[] = '';
                foreach ($c['notes'] as $m) {
                    $out[] = "- {$m}";
                }
            }
            $out[] = '';
            $out[] = "**Expected result:** {$c['expected']}";
            $out[] = '';
            $out[] = '**Next step:** '.($next ? "Chapter {$next['number']} — {$next['title']}" : 'End of the training.');
        }

        return implode("\n", $out)."\n";
    }
}
